[project]
name = "mlkem"
version = "0.1.0"
description = "A module-latice-based key-encapsulation mechanism (ML-KEM). Implements the FIPS-203 standard."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
keywords = ["post-quantum", "cryptography", "fip-203", "kyber", "crystals", "module-lattice-based", "key-encapsulation", "mechanism"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Security :: Cryptography",
    "Programming Language :: C",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Rust",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux"
]

[project.scripts]
benchmark = "mlkem.benchmark:main"

[dependency-groups]
dev = [
    "maturin>=1.15.0",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.9",
    "sphinx>=9.0.4",
    "sphinx-rtd-theme>=3.1.0",
    "ty>=0.0.84",
]

[build-system]
requires = ["maturin>=1.15,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "mlkem.rust"
