name: Publish Python 🐍 distribution 📦 to TestPyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+a[0-9]+'  # only run on alpha tags

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  build_wheels-manylinux:
    name: Build wheels on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: cp311-* cp312-* cp313-*

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-manylinux
          path: ./wheelhouse/*.whl

  # macos-13 is an intel runner
  build_wheels-macos-13:
    name: Build wheels on macos-13
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: cp311-* cp312-* cp313-*
          MACOSX_DEPLOYMENT_TARGET: 13.0

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-macos-13
          path: ./wheelhouse/*.whl

  # macos-14 is apple silicon
  build_wheels-macos-14:
    name: Build wheels on macos-14
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: cp311-* cp312-* cp313-*
          MACOSX_DEPLOYMENT_TARGET: 14.0

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-macos-14
          path: ./wheelhouse/*.whl

  build_wheels-windows:
    name: Build wheels on windows-latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: cp311-* cp312-* cp313-*

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-windows
          path: ./wheelhouse/*.whl

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs: [make_sdist, build_wheels-manylinux, build_wheels-macos-13, build_wheels-macos-14, build_wheels-windows]
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/fastecdsa

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist/
        merge-multiple: true

    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        repository-url: https://test.pypi.org/legacy/
